# -*- coding: utf-8 -*-
"""cvlab 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8vx-81GwI9UhPAPIkpHwbwYJhKg1BhB
"""

import cv2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#load the image in gray
img=cv2.imread('/content/123',cv2.IMREAD_GRAYSCALE)
if img is None:
  print("error: image not found")
else:
  plt.figure(figsize=(12,10))
#display original image
plt.subplot(3,3,1)
plt.imshow(img,cmap='gray')
plt.title('original image')
plt.axis('off')

#loop through all 8 bit planes
for i in range(8):
  #extract the i-th bit plane
  #shift bits right by 'i' and perform bitwise AND with 1
  bit_plane = (img >> i)&1
  #scale to 0-255 for visualization(0 becomes black, 1 becomes white)
  vis_plane = bit_plane*255
  # plotting
  plt.subplot(3, 3, i + 2) #position starts from 2
  plt.imshow(vis_plane, cmap='gray')
  plt.title(f'Bit Plane {i}')
  plt.axis('off')